---
image: docker:18.01.0-ce-git
services:
  - docker:18.01.0-ce-dind
stages:
- build_assets
- run_composer
- create_pack
- deploy
     
variables:
  KUBECONFIG: /etc/k8s-config
  THEME_NAME: midia-ninja-theme
  NAMESPACE_DEV: base-theme-site-dev
  NAMESPACE_PROD: base-theme-site-prod
  AUTH: JOB-TOKEN:$CI_JOB_TOKEN

cache:
   key: base-theme-key
   paths:
     - themes/${THEME_NAME}/dist

########################DEVELOP E PROD################
build_assets:
 stage: build_assets
 only:
   - /main/
   - tags
   - /feat/flickr/


 tags:
   - docker
 image: node:12
 
 script:
   - rm -rf themes/${THEME_NAME}/dist
   - npm --prefix themes/${THEME_NAME}/ install
   - npm --prefix themes/${THEME_NAME}/ run production
   - rm -rf themes/${THEME_NAME}/node_modules

run_composer:
  stage: run_composer
  only:
   - /main/
   - /feat/flickr/
   - tags
  tags:
   - docker
  image: composer:2.9    
  script:
    - cd themes/${THEME_NAME}/
    - composer install

########################DEVELOP#######################
create_pack_develop:
  stage: create_pack
  only:
    - /main/
    - /feat/flickr/

  tags:
    - docker
  image: hacklab/alpine-3.14.2-zip:1.1.0
  script:
    - cd themes/
    - mkdir -p /deploy-zips/
    - zip -r /deploy-zips/${THEME_NAME}.zip ${THEME_NAME}  
    #create theme pack
    - curl --header "$AUTH" --upload-file /deploy-zips/${THEME_NAME}.zip  "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${THEME_NAME}/${CI_COMMIT_SHORT_SHA}/${THEME_NAME}.zip"

deploy_to_develop:
  stage: deploy
  image: hacklab/kubectl:latest
  script:
    - echo ${kubeconfig} | base64 -d > ${KUBECONFIG}
    - POD=$(kubectl get pods -n ${NAMESPACE_DEV} | grep wordpress | cut -d ' ' -f 1) 
    - echo $POD
    #deploy zips to production
    - kubectl exec -n ${NAMESPACE_DEV} -it $POD -- sh -c "cd /tmp/ && curl --create-dirs --location --output /tmp/deploy-zips/${THEME_NAME}.zip  --header $AUTH ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${THEME_NAME}/${CI_COMMIT_SHORT_SHA}/${THEME_NAME}.zip && cd /var/www/html/ && wp theme install --force /tmp/deploy-zips/${THEME_NAME}.zip && chown -R www-data /var/www/html/wp-content/themes/ && chgrp -R www-data /var/www/html/wp-content/themes/"    
  environment: develop
  only:
    - /main/
  tags:
    - docker
########################PROD#######################

create_pack_production:
  stage: create_pack
  only:
    - tags
  tags:
    - docker
  image: hacklab/alpine-3.14.2-zip:1.1.0
  script:
    - cd themes/
    - mkdir -p /deploy-zips/
    - zip -r /deploy-zips/${THEME_NAME}.zip ${THEME_NAME}  
    #create theme pack
    - curl --header "$AUTH" --upload-file /deploy-zips/${THEME_NAME}.zip  "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${THEME_NAME}/${CI_BUILD_REF_NAME}/${THEME_NAME}.zip"

deploy_to_production:
  stage: deploy
  image: hacklab/kubectl:latest
  script:
    - echo ${kubeconfig} | base64 -d > ${KUBECONFIG}
    - POD=$(kubectl get pods -n ${NAMESPACE_PROD} | grep wordpress | cut -d ' ' -f 1) 
    - echo $POD
    #deploy zips to production
    - kubectl exec -n ${NAMESPACE_PROD} -it $POD -- sh -c "cd /tmp/ && curl --create-dirs --location --output /tmp/deploy-zips/${THEME_NAME}.zip  --header $AUTH ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${THEME_NAME}/${CI_BUILD_REF_NAME}/${THEME_NAME}.zip && cd /var/www/html/ && wp theme install --force /tmp/deploy-zips/${THEME_NAME}.zip"    
  environment: develop
  only:
    - tags
  tags:
    - docker
